#!/bin/bash

if test -z "$1" ; then
  echo "Create a new folder and save docker logs generated by test recently executed."
  echo "Usage: $0 <arg1> <arg2>>"
  echo "Example Usage: $0 <pass|fail> <testcaseUniqueString>"
  exit 0
fi

TIMENOW=`date | tr -d ' '`
mkdir logs_$1_$2_$TIMENOW
cd logs_$1_$2_$TIMENOW
   docker logs cli &> cli_$1_$2
   docker logs orderer &> orderer_$1_$2
   docker logs orderer0 &> orderer0_$1_$2
   docker logs orderer1 &> orderer1_$1_$2
   docker logs orderer2 &> orderer2_$1_$2
   docker logs orderer3 &> orderer3_$1_$2
   docker logs kafka0 &> kafka0_$1_$2
   docker logs kafka1 &> kafka1_$1_$2
   docker logs kafka2 &> kafka2_$1_$2
   docker logs kafka3 &> kafka3_$1_$2
   docker logs zookeeper &> zookeeper_$1_$2
   docker logs peer0 &> peer0_$1_$2
   docker logs peer1 &> peer1_$1_$2
   docker logs peer2 &> peer2_$1_$2
   docker logs peer3 &> peer3_$1_$2
